import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  
  // [1] AI 상식사전용 사이드바
  // '01-ai-dictionary' 폴더 안에 있는 파일들만 보여줍니다.
  dictionarySidebar: [
    {
      type: 'autogenerated',
      dirName: '01-ai-dictionary', 
    },
  ],

  // [2] AI 인프라용 사이드바
  infraSidebar: [
    {
      type: 'autogenerated',
      dirName: '02-ai-infra',
    },
  ],

  // [3] AI 공부용 사이드바
  studySidebar: [
    {
      type: 'autogenerated',
      dirName: '03-ai-study',
    },
  ],

  // [4] 공통 기술용 사이드바
  commonSidebar: [
    {
      type: 'autogenerated',
      dirName: '04-common',
    },
  ],
};

export default sidebars;